name: hooliday
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_image_slideshow: ^0.1.6
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  iconsax: ^0.0.8
  intl: ^0.18.1
  page_transition: ^2.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
    # flutter_native_splash: ^2.4.0
    #background_image: 'assets/splash.png'
    #color: '#ffffff'
    #android_12:
    #   image: assets/splash.png
    #  web: false

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/gondola.jpg
    - assets/images/hotel0.jpg
    - assets/images/hotel1.jpg
    - assets/images/hotel2.jpg
    - assets/images/murano.jpg
    - assets/images/newdelhi.jpg
    - assets/images/newyork.jpg
    - assets/images/paris.jpg
    - assets/images/santorini.jpg
    - assets/images/saopaulo.jpg
    - assets/images/stmarksbasilica.jpg
    - assets/images/venice.jpg
    - assets/profile.jpg
    - assets/splash_screen2.jpg
    - assets/images/profile_bkg1.jpg
    - assets/images/profile_bkg2.jpg
    - assets/images/china_new_year.jpg
    - assets/images/oktober_fest.jpg
    - assets/images/diwali_fest.jpg
    - assets/splash/
    - assets/icons/

  fonts:
    - family: Fleur De Leah
      fonts:
        - asset: assets/fonts/FleurDeLeah-Regular.ttf
          #style: Regular
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
