// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbCAwpUASQ5286oc1s_QHb_bJYacLMlbM',
    appId: '1:1078238886240:web:ebb7b088fd9c98114d8605',
    messagingSenderId: '1078238886240',
    projectId: 'hooliday-8c3c1',
    authDomain: 'hooliday-8c3c1.firebaseapp.com',
    storageBucket: 'hooliday-8c3c1.appspot.com',
    measurementId: 'G-5QVNYH4LJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaPHZr4XuHnbgU3JPgZcicZVIL22Pm5zc',
    appId: '1:1078238886240:android:0e129a49835717d44d8605',
    messagingSenderId: '1078238886240',
    projectId: 'hooliday-8c3c1',
    storageBucket: 'hooliday-8c3c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyHtBr4tKhYrY-6IDpmpnnU8VF1geXq1I',
    appId: '1:1078238886240:ios:99ee82637ea532bf4d8605',
    messagingSenderId: '1078238886240',
    projectId: 'hooliday-8c3c1',
    storageBucket: 'hooliday-8c3c1.appspot.com',
    iosBundleId: 'com.example.hooliday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyHtBr4tKhYrY-6IDpmpnnU8VF1geXq1I',
    appId: '1:1078238886240:ios:99ee82637ea532bf4d8605',
    messagingSenderId: '1078238886240',
    projectId: 'hooliday-8c3c1',
    storageBucket: 'hooliday-8c3c1.appspot.com',
    iosBundleId: 'com.example.hooliday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbCAwpUASQ5286oc1s_QHb_bJYacLMlbM',
    appId: '1:1078238886240:web:962dc77bfd4262984d8605',
    messagingSenderId: '1078238886240',
    projectId: 'hooliday-8c3c1',
    authDomain: 'hooliday-8c3c1.firebaseapp.com',
    storageBucket: 'hooliday-8c3c1.appspot.com',
    measurementId: 'G-R489J4KYH7',
  );
}
