// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYcCSjd93e54dqmBJ-UTZEO7Qb_XKmrTc',
    appId: '1:166376407860:web:6db7a8b5d885d9b5321b61',
    messagingSenderId: '166376407860',
    projectId: 'hooliday-92563',
    authDomain: 'hooliday-92563.firebaseapp.com',
    storageBucket: 'hooliday-92563.appspot.com',
    measurementId: 'G-V31M46Q0P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnYFhCpxlYfJmf7BmNCVuZSaX-vpqVnp0',
    appId: '1:166376407860:android:4b48b593f23ebf12321b61',
    messagingSenderId: '166376407860',
    projectId: 'hooliday-92563',
    storageBucket: 'hooliday-92563.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZPFv_ga6HsAJHDSCm9hDCY19s3LS0jvo',
    appId: '1:166376407860:ios:01e946cd937f3e9d321b61',
    messagingSenderId: '166376407860',
    projectId: 'hooliday-92563',
    storageBucket: 'hooliday-92563.appspot.com',
    iosBundleId: 'com.example.hooliday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZPFv_ga6HsAJHDSCm9hDCY19s3LS0jvo',
    appId: '1:166376407860:ios:01e946cd937f3e9d321b61',
    messagingSenderId: '166376407860',
    projectId: 'hooliday-92563',
    storageBucket: 'hooliday-92563.appspot.com',
    iosBundleId: 'com.example.hooliday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYcCSjd93e54dqmBJ-UTZEO7Qb_XKmrTc',
    appId: '1:166376407860:web:19e58eeeb33f9aaa321b61',
    messagingSenderId: '166376407860',
    projectId: 'hooliday-92563',
    authDomain: 'hooliday-92563.firebaseapp.com',
    storageBucket: 'hooliday-92563.appspot.com',
    measurementId: 'G-92JEZWF8BY',
  );
}
